# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: '**/NP.Lti13Platform.csproj'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Patch: $[counter(format('{0}.{1}', variables['Major'], variables['Minor']), 0)]
  BuildVersion: $[format('{0}.{1}.{2}', variables['Major'], variables['Minor'], variables['Patch'])]

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo $(BuildVersion)'

- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 10.x
    performMultiLevelLookup: true
    includePreviewVersions: true

- task: NuGetAuthenticate@1
  displayName: 'NuGet Authenticate'

- script: |
    dotnet restore $(solution)
    dotnet build $(solution)

- task: DotNetCoreCLI@2
  displayName: 'Packing  $(project)'
  inputs:
    command: pack
    packagesToPack: '$(Project)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'BuildVersion'
  
- task: NuGetCommand@2
  displayName: Pushing to feed
  inputs:
    command: 'push'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'b0d25f0a-331d-46ae-9c63-2476b088369a'